<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SysPermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sys_permissions')->delete();
        
        \DB::table('sys_permissions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'admin',
                'guard_name' => 'sanctum',
                'title' => '后台管理系统',
                'url' => NULL,
                '_lft' => 1,
                '_rgt' => 84,
                'parent_id' => NULL,
                'created_at' => '2022-10-05 12:31:20',
                'updated_at' => '2022-10-05 12:31:20',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'system',
                'guard_name' => 'sanctum',
                'title' => '系统设置',
                'url' => NULL,
                '_lft' => 76,
                '_rgt' => 83,
                'parent_id' => 1,
                'created_at' => '2022-10-05 12:33:23',
                'updated_at' => '2023-02-07 14:00:25',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'system.admins',
                'guard_name' => 'sanctum',
                'title' => '管理员',
                'url' => '/system/admins',
                '_lft' => 77,
                '_rgt' => 78,
                'parent_id' => 2,
                'created_at' => '2022-10-05 12:33:50',
                'updated_at' => '2023-02-07 14:00:45',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'system.sys_roles',
                'guard_name' => 'sanctum',
                'title' => '角色',
                'url' => '/system/sys_roles',
                '_lft' => 79,
                '_rgt' => 80,
                'parent_id' => 2,
                'created_at' => '2022-10-05 12:35:32',
                'updated_at' => '2023-02-07 14:00:57',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'system.sys_permissions',
                'guard_name' => 'sanctum',
                'title' => '菜单',
                'url' => '/system/sys_permissions',
                '_lft' => 81,
                '_rgt' => 82,
                'parent_id' => 2,
                'created_at' => '2022-10-05 12:35:52',
                'updated_at' => '2023-02-07 14:01:07',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'configs',
                'guard_name' => 'sanctum',
                'title' => '参数设置',
                'url' => NULL,
                '_lft' => 56,
                '_rgt' => 75,
                'parent_id' => 1,
                'created_at' => '2022-10-08 15:46:52',
                'updated_at' => '2023-02-07 14:07:45',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'others.coins',
                'guard_name' => 'sanctum',
                'title' => 'Coins',
                'url' => '/others/coins',
                '_lft' => 43,
                '_rgt' => 44,
                'parent_id' => 24,
                'created_at' => '2022-10-08 15:47:16',
                'updated_at' => '2023-02-07 14:08:20',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'others.funds',
                'guard_name' => 'sanctum',
                'title' => 'Funds',
                'url' => '/others/funds',
                '_lft' => 45,
                '_rgt' => 46,
                'parent_id' => 24,
                'created_at' => '2022-10-08 15:47:27',
                'updated_at' => '2023-02-07 14:09:19',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'users',
                'guard_name' => 'sanctum',
                'title' => '用户管理',
                'url' => NULL,
                '_lft' => 2,
                '_rgt' => 9,
                'parent_id' => 1,
                'created_at' => '2022-10-08 15:47:37',
                'updated_at' => '2023-02-07 14:01:19',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'users.users',
                'guard_name' => 'sanctum',
                'title' => '用户列表',
                'url' => '/users/users',
                '_lft' => 3,
                '_rgt' => 4,
                'parent_id' => 9,
                'created_at' => '2022-10-08 15:48:01',
                'updated_at' => '2023-02-07 14:01:28',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'jackpots',
                'guard_name' => 'sanctum',
                'title' => '奖池管理',
                'url' => NULL,
                '_lft' => 26,
                '_rgt' => 33,
                'parent_id' => 1,
                'created_at' => '2022-10-08 15:48:25',
                'updated_at' => '2023-02-07 14:03:54',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'jackpots.jackpots',
                'guard_name' => 'sanctum',
                'title' => '奖池列表',
                'url' => '/jackpots/jackpots',
                '_lft' => 27,
                '_rgt' => 28,
                'parent_id' => 11,
                'created_at' => '2022-10-08 15:48:46',
                'updated_at' => '2023-02-07 14:04:12',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'assets',
                'guard_name' => 'sanctum',
                'title' => '资产管理',
                'url' => NULL,
                '_lft' => 10,
                '_rgt' => 19,
                'parent_id' => 1,
                'created_at' => '2022-10-10 11:33:23',
                'updated_at' => '2023-02-07 14:02:42',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'assets.stakings',
                'guard_name' => 'sanctum',
                'title' => '正在质押',
                'url' => '/assets/stakings',
                '_lft' => 11,
                '_rgt' => 12,
                'parent_id' => 13,
                'created_at' => '2022-10-10 11:34:16',
                'updated_at' => '2023-02-07 14:02:57',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'others.vip',
                'guard_name' => 'sanctum',
                'title' => 'Vip',
                'url' => '/others/vips',
                '_lft' => 47,
                '_rgt' => 48,
                'parent_id' => 24,
                'created_at' => '2022-10-10 11:35:28',
                'updated_at' => '2023-02-07 14:09:43',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'jackpots.jackpots_has_users',
                'guard_name' => 'sanctum',
                'title' => '用户贡献',
                'url' => '/jackpots/jackpots_has_users',
                '_lft' => 29,
                '_rgt' => 30,
                'parent_id' => 11,
                'created_at' => '2022-10-10 11:37:10',
                'updated_at' => '2023-02-07 14:04:24',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'jackpots.jackpot_logs',
                'guard_name' => 'sanctum',
                'title' => '奖池日志',
                'url' => '/jackpots/jackpot_logs',
                '_lft' => 31,
                '_rgt' => 32,
                'parent_id' => 11,
                'created_at' => '2022-10-10 11:37:39',
                'updated_at' => '2023-02-07 14:04:33',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'assets.withdrawable',
                'guard_name' => 'sanctum',
                'title' => '可提现',
                'url' => '/assets/withdrawable',
                '_lft' => 13,
                '_rgt' => 14,
                'parent_id' => 13,
                'created_at' => '2022-10-10 11:39:28',
                'updated_at' => '2023-02-07 14:03:10',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'ai_trade',
                'guard_name' => 'sanctum',
                'title' => 'AiTrade',
                'url' => NULL,
                '_lft' => 20,
                '_rgt' => 25,
                'parent_id' => 1,
                'created_at' => '2022-10-10 11:40:17',
                'updated_at' => '2023-02-07 14:04:48',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'users.users.identity',
                'guard_name' => 'sanctum',
                'title' => '身份认证待审核',
                'url' => '/users/users_identity',
                '_lft' => 7,
                '_rgt' => 8,
                'parent_id' => 9,
                'created_at' => '2022-10-10 11:41:57',
                'updated_at' => '2023-02-07 14:02:01',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'users.users.profile',
                'guard_name' => 'sanctum',
                'title' => '个人信息待审核',
                'url' => '/users/users_profile',
                '_lft' => 5,
                '_rgt' => 6,
                'parent_id' => 9,
                'created_at' => '2022-10-10 11:42:31',
                'updated_at' => '2023-02-07 14:01:45',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'ai_trade.pledges',
                'guard_name' => 'sanctum',
                'title' => '计划管理',
                'url' => '/ai_trade/pledges',
                '_lft' => 21,
                '_rgt' => 22,
                'parent_id' => 19,
                'created_at' => '2022-10-10 11:43:42',
                'updated_at' => '2023-02-07 14:05:01',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'ai_trade.profits',
                'guard_name' => 'sanctum',
                'title' => '收益计算',
                'url' => '/ai_trade/profits',
                '_lft' => 23,
                '_rgt' => 24,
                'parent_id' => 19,
                'created_at' => '2022-10-10 11:45:39',
                'updated_at' => '2023-02-07 14:05:23',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'others',
                'guard_name' => 'sanctum',
                'title' => '其他',
                'url' => NULL,
                '_lft' => 34,
                '_rgt' => 51,
                'parent_id' => 1,
                'created_at' => '2022-11-13 09:23:27',
                'updated_at' => '2023-02-07 14:06:07',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'others.subscribes',
                'guard_name' => 'sanctum',
                'title' => '订阅',
                'url' => '/others/subscribes',
                '_lft' => 35,
                '_rgt' => 36,
                'parent_id' => 24,
                'created_at' => '2022-11-13 09:23:50',
                'updated_at' => '2023-02-07 14:06:23',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'others.referrals',
                'guard_name' => 'sanctum',
                'title' => '转介',
                'url' => '/others/referrals',
                '_lft' => 37,
                '_rgt' => 38,
                'parent_id' => 24,
                'created_at' => '2022-11-13 09:25:11',
                'updated_at' => '2023-02-07 14:06:36',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'others.bonus',
                'guard_name' => 'sanctum',
                'title' => '奖励',
                'url' => '/others/bonus',
                '_lft' => 39,
                '_rgt' => 40,
                'parent_id' => 24,
                'created_at' => '2022-11-13 09:25:32',
                'updated_at' => '2023-02-07 14:06:47',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'assets.pendings',
                'guard_name' => 'sanctum',
                'title' => '执行中',
                'url' => '/assets/pendings',
                '_lft' => 15,
                '_rgt' => 16,
                'parent_id' => 13,
                'created_at' => '2022-11-13 09:28:24',
                'updated_at' => '2023-02-07 14:03:24',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'web3',
                'guard_name' => 'sanctum',
                'title' => 'Web3',
                'url' => NULL,
                '_lft' => 52,
                '_rgt' => 55,
                'parent_id' => 1,
                'created_at' => '2022-11-13 13:05:03',
                'updated_at' => '2023-02-07 14:07:23',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'web3.transactions',
                'guard_name' => 'sanctum',
                'title' => 'web3交易',
                'url' => '/web3/transactions',
                '_lft' => 53,
                '_rgt' => 54,
                'parent_id' => 29,
                'created_at' => '2022-11-13 13:05:22',
                'updated_at' => '2023-02-07 14:07:16',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'configs.user_kill',
                'guard_name' => 'sanctum',
                'title' => 'User Kill',
                'url' => '/configs/user_kill',
                '_lft' => 59,
                '_rgt' => 60,
                'parent_id' => 6,
                'created_at' => '2022-11-13 13:06:24',
                'updated_at' => '2023-02-10 09:49:08',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'configs.trail_kill',
                'guard_name' => 'sanctum',
                'title' => 'Trail Kill',
                'url' => '/configs/trail_kill',
                '_lft' => 57,
                '_rgt' => 58,
                'parent_id' => 6,
                'created_at' => '2022-11-13 13:07:06',
                'updated_at' => '2023-02-10 09:49:20',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'assets.withdraw_approve',
                'guard_name' => 'sanctum',
                'title' => '提现审核',
                'url' => '/assets/withdraw_approve',
                '_lft' => 17,
                '_rgt' => 18,
                'parent_id' => 13,
                'created_at' => '2022-11-14 12:39:21',
                'updated_at' => '2023-02-07 14:03:32',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'others.cases',
                'guard_name' => 'sanctum',
                'title' => '支持',
                'url' => '/others/cases',
                '_lft' => 41,
                '_rgt' => 42,
                'parent_id' => 24,
                'created_at' => '2023-01-14 09:18:57',
                'updated_at' => '2023-02-07 14:06:56',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'configs.gift',
                'guard_name' => 'sanctum',
                'title' => '礼物设置',
                'url' => '/configs/gift',
                '_lft' => 65,
                '_rgt' => 66,
                'parent_id' => 6,
                'created_at' => '2023-02-07 14:11:38',
                'updated_at' => '2023-02-10 09:50:53',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'configs.profit',
                'guard_name' => 'sanctum',
                'title' => 'APY设置',
                'url' => '/configs/profit',
                '_lft' => 67,
                '_rgt' => 68,
                'parent_id' => 6,
                'created_at' => '2023-02-07 14:12:11',
                'updated_at' => '2023-02-10 09:50:59',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'configs.vip_kill',
                'guard_name' => 'sanctum',
                'title' => 'Vip Kill',
                'url' => '/configs/vip_kill',
                '_lft' => 61,
                '_rgt' => 62,
                'parent_id' => 6,
                'created_at' => '2023-02-10 09:49:57',
                'updated_at' => '2023-02-10 09:50:07',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'configs.address',
                'guard_name' => 'sanctum',
                'title' => '地址设置',
                'url' => '/configs/address',
                '_lft' => 63,
                '_rgt' => 64,
                'parent_id' => 6,
                'created_at' => '2023-02-10 09:50:24',
                'updated_at' => '2023-02-10 09:50:47',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'configs.fee',
                'guard_name' => 'sanctum',
                'title' => '手续费设置',
                'url' => '/configs/fee',
                '_lft' => 69,
                '_rgt' => 70,
                'parent_id' => 6,
                'created_at' => '2023-02-10 09:51:22',
                'updated_at' => '2023-02-10 09:51:22',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'configs.others',
                'guard_name' => 'sanctum',
                'title' => '其他设置',
                'url' => '/configs/others',
                '_lft' => 71,
                '_rgt' => 72,
                'parent_id' => 6,
                'created_at' => '2023-02-10 09:51:43',
                'updated_at' => '2023-02-10 09:51:43',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'other.sys_messages',
                'guard_name' => 'sanctum',
                'title' => '消息群发',
                'url' => '/other/sys_messages',
                '_lft' => 49,
                '_rgt' => 50,
                'parent_id' => 24,
                'created_at' => '2023-02-11 03:31:51',
                'updated_at' => '2023-02-11 03:31:51',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'configs.trail',
                'guard_name' => 'sanctum',
                'title' => 'Trail Setting',
                'url' => '/configs/trail',
                '_lft' => 73,
                '_rgt' => 74,
                'parent_id' => 6,
                'created_at' => '2023-03-07 15:21:11',
                'updated_at' => '2023-03-07 15:21:11',
            ),
        ));
        
        
    }
}