<?php

namespace Tests\Helpers\CoinGecko;


use App\Helpers\CoinGecko\CGProApi;
use Tests\TestCase;

class CGProApiTest extends TestCase
{
    private CGProApi $api;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->api = new CGProApi();
    }

    public function testCoinsMarketChart()
    {
        $res = $this->api->coinsMarketChart('solana')['prices'];
        $data = array_column($res, 1);
        dump($data);
    }

    public function testSimplePrice()
    {
        dd($this->api->simplePrice('tether'));
    }

    public function testCoinsMarkets()
    {
    }

    public function testCoins()
    {

    }
}
