<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use LaravelCommon\App\Traits\TestCaseTrait;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    use TestCaseTrait;

    protected array $headers = [
        'account' => '{"address":"0x6034Ad1244b398d583ac3C4C4291be10Ac831C41","wallet":"","network":"","invite_code":"","chain":"Ethereum","isConnected":true,"isLogin":true}'
    ];

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->token = '49|EvVKfDGSyNdTuc6botOpvTeSu2riKkxj3AQRvNH2';
    }
}
