<?php

namespace Tests\Helpers\Web3;


use App\Helpers\Web3\ErcWeb3Helper;
use Tests\TestCase;

class ErcWeb3HelperTest extends TestCase
{
    private ErcWeb3Helper $helper;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->helper = new ErcWeb3Helper();
    }

    public function testSend()
    {

    }

    public function testSendToken()
    {

    }

    public function testGetTokenBalance()
    {

    }

    public function testGetTransactionsByAddress()
    {

    }

    public function testGetTransactionByHash()
    {
        // cb 转
        dump($this->helper->GetTransactionByHash('0x0ceb7d4d62ec3df7bcdd7986bac1d956dd691b7fdca53d4e46701b929b7ca049', debug: true, toAddress: '0x92d0595734F3DC469C48D539a3188607B9FA5E11'));
        // wallet 转
//        dump($this->helper->GetTransactionByHash('0xbf334c3f648f19afc12687c6cf1b1182184c8bb2ab7c94424b47a5917de465e2'));

    }
}
